# Generated by Django 2.2.1 on 2019-05-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190518_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='descripition',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='images',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
