# Generated by Django 2.2.1 on 2019-05-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190518_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='descripition',
            new_name='description',
        ),
    ]
