# Generated by Django 2.2.1 on 2019-05-19 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor_class',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sys_id', models.AutoField(default=uuid.UUID('fd5799d2-f31f-4a20-81b6-b7c395974d72'), primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('username', models.CharField(default=None, max_length=500)),
                ('password', models.CharField(default=None, max_length=500)),
                ('first_name', models.CharField(default=None, max_length=500)),
                ('last_name', models.CharField(default=None, max_length=500)),
                ('forfait_hour', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.RemoveField(
            model_name='forfait',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserModel'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='instructor_class',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_content_type', to='polls.UserModel'),
        ),
        migrations.AddField(
            model_name='instructor_class',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserModel'),
        ),
    ]
