# Generated by Django 2.2.1 on 2019-05-19 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190519_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_class',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='polls.UserModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sys_id',
            field=models.AutoField(default=uuid.UUID('c5571800-eefc-4b1d-8c7f-57ef44246806'), primary_key=True, serialize=False),
        ),
    ]
