# Generated by Django 2.2.1 on 2019-05-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190519_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='is_active',
        ),
    ]
