# Generated by Django 2.2.1 on 2019-05-19 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_userprofil_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=500, unique=True)),
                ('first_name', models.CharField(default=None, max_length=500)),
                ('last_name', models.CharField(default=None, max_length=500)),
                ('email', models.CharField(default=None, max_length=500)),
                ('password', models.CharField(default=None, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('forfait_hour', models.IntegerField()),
                ('images', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointement',
            name='user',
        ),
        migrations.AlterField(
            model_name='instructor_class',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_content_type', to='polls.UserModel'),
        ),
        migrations.AlterField(
            model_name='instructor_class',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_content_type', to='polls.UserModel'),
        ),
        migrations.DeleteModel(
            name='UserProfil',
        ),
        migrations.AddField(
            model_name='appointement',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.UserModel'),
        ),
    ]
