# Generated by Django 2.2.1 on 2019-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190519_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default=None, max_length=500),
        ),
    ]
