# Generated by Django 2.2.1 on 2019-06-01 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190531_2119'),
    ]

    operations = [
    ]
    
    print('migrate')