# Generated by Django 2.2.1 on 2019-06-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20190601_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointement',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='appointement',
            old_name='student_id',
            new_name='student',
        ),
    ]
