# Generated by Django 2.2.1 on 2019-06-02 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190602_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='get_students',
            field=models.ManyToManyField(blank=True, related_name='_usermodel_get_students_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Instructor_class',
        ),
    ]
