# Generated by Django 2.2.1 on 2019-06-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190602_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='forfait_hour',
            field=models.IntegerField(default=20),
        ),
    ]
